# Generated by Django 5.1.2 on 2024-11-11 22:27

import NASAMainPage.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_name", models.CharField(max_length=200)),
                ("dataset_number_of_images", models.IntegerField(editable=False)),
                ("dataset_description", models.TextField()),
                (
                    "dataset_zip",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="NASAMainPage/static/temp/",
                        validators=[NASAMainPage.models.validate_zip_file],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsertDatasetZip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_zip",
                    models.FileField(
                        upload_to="NASAMainPage/static/temp/",
                        validators=[NASAMainPage.models.validate_zip_file],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=200)),
                (
                    "model_path",
                    models.FileField(
                        upload_to="uploads/",
                        validators=[NASAMainPage.models.validate_zip_file],
                    ),
                ),
                ("model_image", models.ImageField(upload_to="")),
                ("model_description", models.TextField()),
                (
                    "model_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NASAMainPage.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatasetClasses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_class_name", models.CharField(max_length=200)),
                ("class_number_of_images", models.IntegerField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NASAMainPage.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fold_number", models.IntegerField()),
                ("confusion_matrix", models.ImageField(upload_to="")),
                ("precision", models.IntegerField()),
                ("recall", models.IntegerField()),
                ("f1score", models.IntegerField()),
                ("support", models.IntegerField()),
                ("accuracy", models.IntegerField()),
                (
                    "AI_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NASAMainPage.aimodel",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NASAMainPage.dataset",
                    ),
                ),
                (
                    "dataset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NASAMainPage.datasetclasses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="temp/",
                        validators=[NASAMainPage.models.validate_picture_file],
                    ),
                ),
                ("image_name", models.CharField(blank=True, max_length=200)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NASAMainPage.dataset",
                    ),
                ),
                (
                    "dataset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NASAMainPage.datasetclasses",
                    ),
                ),
            ],
        ),
    ]
