# Generated by Django 5.1.2 on 2024-11-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_classifier', models.CharField(max_length=200)),
                ('image', models.ImageField(height_field=227, upload_to='', width_field=227)),
                ('image_name', models.CharField(max_length=200)),
                ('dataset_name', models.CharField(max_length=200)),
            ],
        ),
    ]
