# Generated by Django 5.1.2 on 2024-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='model_path',
            field=models.FileField(default='test', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
