# Generated by Django 5.1.2 on 2024-11-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0003_dataset_remove_picture_dataset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fold',
            name='fold_number',
            field=models.IntegerField(),
        ),
    ]
