# Generated by Django 5.1.2 on 2024-11-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0004_remove_fold_dataset_class_remove_fold_f1score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='support',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
