# Generated by Django 5.1.2 on 2024-11-20 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0005_classinfo_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='fold_id',
        ),
        migrations.AddField(
            model_name='fold',
            name='fold_class_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NASAMainPage.classinfo'),
            preserve_default=False,
        ),
    ]
