# Generated by Django 5.1.2 on 2024-11-21 21:12
from optparse import NO_DEFAULT
from types import NoneType

import django.db.models.deletion
from django.db import migrations, models
from django.db.models.fields.mixins import NOT_PROVIDED


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0007_classinfo_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.TextField()),
                ('section_information', models.TextField()),
                ('section_image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fold',
            name='excel_file',
        ),
        migrations.RemoveField(
            model_name='fold',
            name='fold_class_info',
        ),
        migrations.AddField(
            model_name='classinfo',
            name='fold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NASAMainPage.fold'),
            preserve_default=False,
        ),
    ]
