# Generated by Django 5.1.2 on 2024-11-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0009_remove_fold_accuracy_remove_fold_confusion_matrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fold',
            name='fold_name',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
