# Generated by Django 5.1.2 on 2024-11-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0010_fold_fold_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustomSections',
        ),
    ]
