# Generated by Django 5.1.2 on 2024-11-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0011_delete_usercustomsections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldclassinfo',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='foldinfo',
            name='accuracy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fold',
            name='fold_name',
            field=models.CharField(max_length=200),
        ),
    ]
