# Generated by Django 5.1.2 on 2024-11-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0012_remove_foldclassinfo_accuracy_foldinfo_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldclassinfo',
            name='f1score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foldclassinfo',
            name='precision',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foldclassinfo',
            name='recall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foldclassinfo',
            name='support',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foldinfo',
            name='accuracy',
            field=models.FloatField(),
        ),
    ]
