# Generated by Django 5.1.2 on 2024-11-22 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0013_alter_foldclassinfo_f1score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldinfo',
            name='confusion_matrix',
            field=models.ImageField(upload_to='NASAMainPage/static/images/models'),
        ),
        migrations.CreateModel(
            name='UserSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('section_info', models.TextField()),
                ('section_image', models.ImageField(upload_to='')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NASAMainPage.aimodel')),
            ],
        ),
    ]
