# Generated by Django 5.1.2 on 2024-11-25 02:33

import NASAMainPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NASAMainPage", "0015_alter_usersections_section_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="model_path",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="NASAMainPage/static/temp",
                validators=[NASAMainPage.models.validate_zip_file],
            ),
        ),
    ]
