# Generated by Django 5.0.6 on 2025-04-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0017_definition_leaderboard_alter_aimodel_model_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='image_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NASAMainPage.datasetclasses'),
            preserve_default=False,
        ),
    ]
