# Generated by Django 5.0.6 on 2025-04-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0019_remove_round_image_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
    ]
