# Generated by Django 5.0.6 on 2025-04-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0020_game_current_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='ai_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
