# Generated by Django 5.0.6 on 2025-04-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0021_round_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='ai_answer',
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='ai_time',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='player_answer',
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='player_time',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
