# Generated by Django 5.0.6 on 2025-04-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0022_round_ai_answer_round_ai_time_round_player_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='player_time',
        ),
        migrations.AlterField(
            model_name='round',
            name='ai_time',
            field=models.FloatField(),
        ),
    ]
