# Generated by Django 5.0.6 on 2025-04-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0023_remove_round_player_time_alter_round_ai_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='correct_answer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
