# Generated by Django 5.0.6 on 2025-04-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0027_round_player_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai_number_correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='ai_number_incorrect',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='ai_total_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
