# Generated by Django 5.0.6 on 2025-04-07 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASAMainPage', '0028_game_ai_number_correct_game_ai_number_incorrect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='ai_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NASAMainPage.aimodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='ai_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NASAMainPage.dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='game_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NASAMainPage.game'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Scoreboard',
        ),
    ]
